import { ITodoList, TodoItem } from './Todo';

export interface ToDoPageProps {
  [key: string]: any;
}

export const mockData: TodoItem[] = [
  {
    id: '1',
    dir: 'Work',
    desc: 'Finish report',
    title: 'Finish report',
    date: '2023-05-24',
    completed: false,
    favorite: true,
  },
  // {
  //   id: '2',
  //   dir: 'Home',
  //   desc: 'Buy groceries',
  //   title: 'Buy groceries',
  //   date: '2023-05-25',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '3',
  //   dir: 'test',
  //   desc: 'Schedule meeting',
  //   title: 'Schedule meeting',
  //   date: '2023-05-26',
  //   completed: true,
  //   favorite: true,
  // },
  // {
  //   id: '4',
  //   dir: 'Work',
  //   desc: 'Prepare presentation',
  //   title: 'Prepare presentation',
  //   date: '2023-05-27',
  //   completed: false,
  //   favorite: true,
  // },
  // {
  //   id: '5',
  //   dir: 'Home',
  //   desc: 'Clean the house',
  //   title: 'Clean the house',
  //   date: '2023-05-28',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '6',
  //   dir: 'Personal',
  //   desc: 'Go for a run',
  //   title: 'Go for a run',
  //   date: '2023-05-29',
  //   completed: false,
  //   favorite: true,
  // },
  // {
  //   id: '7',
  //   dir: 'Work',
  //   desc: 'Attend team meeting',
  //   title: 'Attend team meeting',
  //   date: '2023-05-30',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '8',
  //   dir: 'Home',
  //   desc: 'Pay bills',
  //   title: 'Pay bills',
  //   date: '2023-05-31',
  //   completed: false,
  //   favorite: true,
  // },
  // {
  //   id: '10',
  //   dir: 'Work',
  //   desc: 'Read a book',
  //   title: 'Read a book',
  //   date: '2023-06-01',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '11',
  //   dir: 'Work',
  //   desc: 'Read a book',
  //   title: 'Read a book',
  //   date: '2023-06-01',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '12',
  //   dir: 'Work',
  //   desc: 'Read a book',
  //   title: 'Read a book',
  //   date: '2023-06-01',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '13',
  //   dir: 'Work',
  //   desc: 'Read a book',
  //   title: 'Read a book',
  //   date: '2023-06-01',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '14',
  //   dir: 'Work',
  //   desc: 'Read a book',
  //   title: 'Read a book',
  //   date: '2023-06-01',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '15',
  //   dir: 'Work',
  //   desc: 'Read a book',
  //   title: 'Read a book',
  //   date: '2023-06-01',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '16',
  //   dir: 'Work',
  //   desc: 'Read a book',
  //   title: 'Read a book',
  //   date: '2023-06-01',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '17',
  //   dir: 'Work',
  //   desc: 'Read a book',
  //   title: 'Read a book',
  //   date: '2023-06-01',
  //   completed: false,
  //   favorite: false,
  // },
  // {
  //   id: '18',
  //   dir: 'Work',
  //   desc: 'Read a book',
  //   title: 'Read a book',
  //   date: '2023-06-01',
  //   completed: false,
  //   favorite: false,
  // },
];
